version: '3.9'

services:
  voting-app:
    build: ./voting-app
    container_name: voting-app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  worker:
    build: ./worker
    container_name: worker
    depends_on:
      - redis
      - db
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db

  result-app:
    build: ./result-app
    container_name: result-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  db:
    image: postgres:alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: recommender
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
